// Catálogo real (perfumes das listagens) + filtros
const PRICE_FILTER_MAX = 800;

function makeProduct(p) {
  const gallery = p.gallery || [p.image, p.image, p.image, p.image];
  const variants = p.variants || [{ size: p.volume || "100ml", price: p.price, label: p.volume || "100ml" }];
  return {
    rating: 4.8,
    reviews: 48,
    oldPrice: null,
    badge: "",
    family: "floral",
    intensity: "edp",
    occasion: "dia",
    sensation: "romantico",
    notes: "Boa fixação e projeção",
    pyramid: {
      top: "Notas de saída",
      heart: "Notas de coração",
      base: "Notas de fundo"
    },
    description: `${p.title}. Perfume original.`,
    ritual: "Borrife nos pulsos e na nuca.",
    ingredients: "Alcohol Denat, Parfum (Fragrance), Aqua.",
    similarIds: [],
    ...p,
    gallery,
    variants
  };
}

const APP_STATE = {
  activeProductId: null,
  selectedPdpVariantIdx: 0,
  pdpQuantity: 1,
  products: [
    makeProduct({
      id: 1,
      title: "Jean Paul Gaultier La Belle Feminino Eau de Parfum",
      brandTag: "JEAN PAUL GAULTIER",
      volume: "Eau de Parfum • 100ml",
      category: "perfumes",
      family: "floral",
      intensity: "edp",
      occasion: "noite",
      sensation: "romantico",
      price: 403.90,
      oldPrice: 449.90,
      badge: "Mais Vendido",
      image: "https://images.unsplash.com/photo-1541643600914-78b084683601?auto=format&fit=crop&w=900&q=85",
      notes: "Pêra, Flor de Laranjeira e Baunilha",
      similarIds: [2, 3, 6, 14]
    }),
    makeProduct({
      id: 2,
      title: "Jean Paul Gaultier La Belle Feminino Le Parfum",
      brandTag: "JEAN PAUL GAULTIER",
      volume: "Le Parfum • 100ml",
      category: "perfumes",
      family: "oriental",
      intensity: "edp",
      occasion: "noite",
      sensation: "marcante",
      price: 444.90,
      oldPrice: 489.90,
      badge: "Lançamento",
      image: "https://images.unsplash.com/photo-1588405748880-12d1d2a59f75?auto=format&fit=crop&w=900&q=85",
      notes: "Pêra Assada, Flor de Laranjeira e Baunilha Bourbon",
      similarIds: [1, 3, 13, 14]
    }),
    makeProduct({
      id: 3,
      title: "Jean Paul Gaultier Scandal Feminino Eau de Parfum",
      brandTag: "JEAN PAUL GAULTIER",
      volume: "Eau de Parfum • 80ml",
      category: "perfumes",
      family: "floral",
      intensity: "edp",
      occasion: "festa",
      sensation: "marcante",
      price: 419.90,
      oldPrice: 459.90,
      badge: "Mais Vendido",
      image: "https://images.unsplash.com/photo-1592945403244-b3fbafd7f539?auto=format&fit=crop&w=900&q=85",
      notes: "Mel, Gardenia e Patchouli",
      similarIds: [4, 1, 12, 14]
    }),
    makeProduct({
      id: 4,
      title: "Jean Paul Gaultier Scandal A Paris Feminino",
      brandTag: "JEAN PAUL GAULTIER",
      volume: "Eau de Toilette • 80ml",
      category: "perfumes",
      family: "floral",
      intensity: "edt",
      occasion: "dia",
      sensation: "romantico",
      price: 361.90,
      oldPrice: 399.90,
      badge: "",
      image: "https://images.unsplash.com/photo-1547887537-6158d64c35b3?auto=format&fit=crop&w=900&q=85",
      notes: "Mel, Peônia e Patchouli",
      similarIds: [3, 1, 6, 15]
    }),
    makeProduct({
      id: 5,
      title: "Animale Seduction Homme Masculino Eau de Toilette",
      brandTag: "ANIMALE",
      volume: "Eau de Toilette • 100ml",
      category: "perfumes",
      family: "amadeirado",
      intensity: "edt",
      occasion: "noite",
      sensation: "marcante",
      price: 276.90,
      oldPrice: 319.90,
      badge: "",
      image: "https://images.unsplash.com/photo-1523293182086-7651a899d37f?auto=format&fit=crop&w=900&q=85",
      notes: "Lavanda, Cardamomo e Madeiras",
      similarIds: [16, 8, 9, 27]
    }),
    makeProduct({
      id: 6,
      title: "Jean Paul Gaultier Classique Feminino Eau de Toilette",
      brandTag: "JEAN PAUL GAULTIER",
      volume: "Eau de Toilette • 100ml",
      category: "perfumes",
      family: "floral",
      intensity: "edt",
      occasion: "dia",
      sensation: "romantico",
      price: 363.90,
      oldPrice: 399.90,
      badge: "",
      image: "https://images.unsplash.com/photo-1595425970377-c9703cf48b6d?auto=format&fit=crop&w=900&q=85",
      notes: "Laranja, Rosa e Baunilha",
      similarIds: [7, 1, 4, 15]
    }),
    makeProduct({
      id: 7,
      title: "Jean Paul Gaultier Classique Feminino Eau de Parfum",
      brandTag: "JEAN PAUL GAULTIER",
      volume: "Eau de Parfum • 100ml",
      category: "perfumes",
      family: "floral",
      intensity: "edp",
      occasion: "noite",
      sensation: "romantico",
      price: 379.90,
      oldPrice: 419.90,
      badge: "Edição Especial",
      image: "https://images.unsplash.com/photo-1594035910387-fea47794261f?auto=format&fit=crop&w=900&q=85",
      notes: "Flor de Laranjeira, Rosa e Baunilha",
      similarIds: [6, 1, 2, 20]
    }),
    makeProduct({
      id: 8,
      title: "Jean Paul Gaultier Ultra Male Masculino Eau de Toilette",
      brandTag: "JEAN PAUL GAULTIER",
      volume: "Eau de Toilette • 125ml",
      category: "perfumes",
      family: "oriental",
      intensity: "edt",
      occasion: "noite",
      sensation: "marcante",
      price: 406.90,
      oldPrice: 449.90,
      badge: "Mais Vendido",
      image: "https://images.unsplash.com/photo-1615634260167-c8cdede054de?auto=format&fit=crop&w=900&q=85",
      notes: "Pera, Lavanda e Baunilha",
      similarIds: [9, 5, 11, 19]
    }),
    makeProduct({
      id: 9,
      title: "Jean Paul Gaultier Le Male Masculino Eau de Toilette",
      brandTag: "JEAN PAUL GAULTIER",
      volume: "Eau de Toilette • 125ml",
      category: "perfumes",
      family: "oriental",
      intensity: "edt",
      occasion: "dia",
      sensation: "marcante",
      price: 347.90,
      oldPrice: 389.90,
      badge: "",
      image: "https://images.unsplash.com/photo-1590736969955-71cc94901144?auto=format&fit=crop&w=900&q=85",
      notes: "Menta, Lavanda e Baunilha",
      similarIds: [8, 11, 5, 18]
    }),
    makeProduct({
      id: 10,
      title: "Coffret Jean Paul Gaultier Divine Feminino",
      brandTag: "JEAN PAUL GAULTIER",
      volume: "Kit presente • EDP + travel",
      category: "kits",
      family: "floral",
      intensity: "edp",
      occasion: "festa",
      sensation: "romantico",
      giftPackaging: "caixa-luxo",
      giftOccasion: "amor",
      price: 702.90,
      oldPrice: 789.90,
      badge: "Edição Especial",
      image: "https://images.unsplash.com/photo-1615634260167-c8cdede054de?auto=format&fit=crop&w=900&q=85",
      notes: "Kit Divine com fragrância e itens complementares",
      similarIds: [11, 12, 1, 13]
    }),
    makeProduct({
      id: 11,
      title: "Coffret Jean Paul Gaultier Le Male Masculino",
      brandTag: "JEAN PAUL GAULTIER",
      volume: "Kit presente • EDT + gel",
      category: "kits",
      family: "oriental",
      intensity: "edt",
      occasion: "noite",
      sensation: "marcante",
      giftPackaging: "caixa-luxo",
      giftOccasion: "amor",
      price: 657.90,
      oldPrice: 729.90,
      badge: "",
      image: "https://images.unsplash.com/photo-1541643600914-78b084683601?auto=format&fit=crop&w=900&q=85",
      notes: "Kit Le Male com fragrância e gel de banho",
      similarIds: [10, 12, 9, 8]
    }),
    makeProduct({
      id: 12,
      title: "Coffret Jean Paul Gaultier Scandal For Him",
      brandTag: "JEAN PAUL GAULTIER",
      volume: "Kit presente • EDT + gel",
      category: "kits",
      family: "oriental",
      intensity: "edt",
      occasion: "festa",
      sensation: "marcante",
      giftPackaging: "caixa-luxo",
      giftOccasion: "amor",
      price: 569.90,
      oldPrice: 629.90,
      badge: "Lançamento",
      image: "https://images.unsplash.com/photo-1588405748880-12d1d2a59f75?auto=format&fit=crop&w=900&q=85",
      notes: "Kit Scandal For Him com fragrância e gel",
      similarIds: [10, 11, 3, 8]
    }),
    makeProduct({
      id: 13,
      title: "Carolina Herrera Good Girl Gold Fantasy Feminino",
      brandTag: "CAROLINA HERRERA",
      volume: "Eau de Parfum • 80ml",
      category: "perfumes",
      family: "oriental",
      intensity: "edp",
      occasion: "festa",
      sensation: "marcante",
      price: 557.90,
      oldPrice: 619.90,
      badge: "Edição Especial",
      image: "https://images.unsplash.com/photo-1592945403244-b3fbafd7f539?auto=format&fit=crop&w=900&q=85",
      notes: "Amêndoa, Café e Cacau",
      similarIds: [14, 15, 17, 2]
    }),
    makeProduct({
      id: 14,
      title: "Carolina Herrera Good Girl Blush Feminino Eau de Parfum",
      brandTag: "CAROLINA HERRERA",
      volume: "Eau de Parfum • 80ml",
      category: "perfumes",
      family: "floral",
      intensity: "edp",
      occasion: "noite",
      sensation: "romantico",
      price: 452.90,
      oldPrice: 499.90,
      badge: "Lançamento",
      image: "https://images.unsplash.com/photo-1547887537-6158d64c35b3?auto=format&fit=crop&w=900&q=85",
      notes: "Lichia, Rosa e Baunilha",
      similarIds: [13, 15, 1, 21]
    }),
    makeProduct({
      id: 15,
      title: "Carolina Herrera 212 Vip Rose I Love NY Feminino",
      brandTag: "CAROLINA HERRERA",
      volume: "Eau de Parfum • 80ml",
      category: "perfumes",
      family: "floral",
      intensity: "edp",
      occasion: "festa",
      sensation: "romantico",
      price: 589.90,
      oldPrice: 649.90,
      badge: "Mais Vendido",
      image: "https://images.unsplash.com/photo-1594035910387-fea47794261f?auto=format&fit=crop&w=900&q=85",
      notes: "Champagne Rosé, Flor de Laranjeira e Almíscar",
      similarIds: [25, 14, 13, 17]
    }),
    makeProduct({
      id: 16,
      title: "Animale Seduction Femme Feminino Eau de Parfum",
      brandTag: "ANIMALE",
      volume: "Eau de Parfum • 100ml",
      category: "perfumes",
      family: "floral",
      intensity: "edp",
      occasion: "noite",
      sensation: "romantico",
      price: 335.90,
      oldPrice: 369.90,
      badge: "",
      image: "https://images.unsplash.com/photo-1595425970377-c9703cf48b6d?auto=format&fit=crop&w=900&q=85",
      notes: "Frutas vermelhas, Florais e Âmbar",
      similarIds: [27, 5, 4, 6]
    }),
    makeProduct({
      id: 17,
      title: "Carolina Herrera CH HC Pasion Feminino Eau de Parfum",
      brandTag: "CAROLINA HERRERA",
      volume: "Eau de Parfum • 100ml",
      category: "perfumes",
      family: "oriental",
      intensity: "edp",
      occasion: "noite",
      sensation: "marcante",
      price: 751.90,
      oldPrice: 829.90,
      badge: "Edição Especial",
      image: "https://images.unsplash.com/photo-1523293182086-7651a899d37f?auto=format&fit=crop&w=900&q=85",
      notes: "Frutas tropicais, Rosa e Madeiras",
      similarIds: [22, 13, 15, 23]
    }),
    makeProduct({
      id: 18,
      title: "Giorgio Armani Acqua Di Gio Homme Profondo",
      brandTag: "GIORGIO ARMANI",
      volume: "Eau de Parfum • 75ml",
      category: "perfumes",
      family: "amadeirado",
      intensity: "edp",
      occasion: "dia",
      sensation: "marcante",
      price: 483.90,
      oldPrice: 539.90,
      badge: "",
      image: "https://images.unsplash.com/photo-1615634260167-c8cdede054de?auto=format&fit=crop&w=900&q=85",
      notes: "Notas marinhas, Patchouli e Almíscar",
      similarIds: [26, 28, 24, 19]
    }),
    makeProduct({
      id: 19,
      title: "Giorgio Armani Code Masculino Eau de Toilette",
      brandTag: "GIORGIO ARMANI",
      volume: "Eau de Toilette • 125ml",
      category: "perfumes",
      family: "oriental",
      intensity: "edt",
      occasion: "noite",
      sensation: "marcante",
      price: 643.90,
      oldPrice: 709.90,
      badge: "Mais Vendido",
      image: "https://images.unsplash.com/photo-1590736969955-71cc94901144?auto=format&fit=crop&w=900&q=85",
      notes: "Limão, Azeitona e Guaiac Wood",
      similarIds: [20, 18, 28, 8]
    }),
    makeProduct({
      id: 20,
      title: "Giorgio Armani Code Femme Feminino Eau de Parfum",
      brandTag: "GIORGIO ARMANI",
      volume: "Eau de Parfum • 75ml",
      category: "perfumes",
      family: "floral",
      intensity: "edp",
      occasion: "noite",
      sensation: "romantico",
      price: 598.90,
      oldPrice: 659.90,
      badge: "",
      image: "https://images.unsplash.com/photo-1541643600914-78b084683601?auto=format&fit=crop&w=900&q=85",
      notes: "Laranja, Jasmim e Mel",
      similarIds: [19, 21, 23, 14]
    }),
    makeProduct({
      id: 21,
      title: "Giorgio Armani Si Feminino Eau de Parfum",
      brandTag: "GIORGIO ARMANI",
      volume: "Eau de Parfum • 100ml",
      category: "perfumes",
      family: "floral",
      intensity: "edp",
      occasion: "dia",
      sensation: "romantico",
      price: 552.90,
      oldPrice: 609.90,
      badge: "",
      image: "https://images.unsplash.com/photo-1588405748880-12d1d2a59f75?auto=format&fit=crop&w=900&q=85",
      notes: "Cassis, Rosa Livre e Baunilha",
      similarIds: [23, 20, 24, 14]
    }),
    makeProduct({
      id: 22,
      title: "Carolina Herrera CH HC Pasion Masculino Eau de Toilette",
      brandTag: "CAROLINA HERRERA",
      volume: "Eau de Toilette • 100ml",
      category: "perfumes",
      family: "oriental",
      intensity: "edt",
      occasion: "noite",
      sensation: "marcante",
      price: 622.90,
      oldPrice: 689.90,
      badge: "Lançamento",
      image: "https://images.unsplash.com/photo-1592945403244-b3fbafd7f539?auto=format&fit=crop&w=900&q=85",
      notes: "Laranja, Canela e Âmbar",
      similarIds: [17, 29, 25, 19]
    }),
    makeProduct({
      id: 23,
      title: "Giorgio Armani Si Passione Feminino Eau de Parfum",
      brandTag: "GIORGIO ARMANI",
      volume: "Eau de Parfum • 100ml",
      category: "perfumes",
      family: "floral",
      intensity: "edp",
      occasion: "festa",
      sensation: "marcante",
      price: 552.90,
      oldPrice: 609.90,
      badge: "Mais Vendido",
      image: "https://images.unsplash.com/photo-1547887537-6158d64c35b3?auto=format&fit=crop&w=900&q=85",
      notes: "Pimenta Rosa, Rosa e Baunilha",
      similarIds: [21, 20, 14, 1]
    }),
    makeProduct({
      id: 24,
      title: "Giorgio Armani Acqua di Gioia Feminino Eau de Parfum",
      brandTag: "GIORGIO ARMANI",
      volume: "Eau de Parfum • 100ml",
      category: "perfumes",
      family: "floral",
      intensity: "edp",
      occasion: "dia",
      sensation: "romantico",
      price: 459.90,
      oldPrice: 509.90,
      badge: "",
      image: "https://images.unsplash.com/photo-1594035910387-fea47794261f?auto=format&fit=crop&w=900&q=85",
      notes: "Limão, Hortelã e Cedro",
      similarIds: [21, 18, 28, 16]
    }),
    makeProduct({
      id: 25,
      title: "Carolina Herrera 212 VIP Black I Love NY Masculino",
      brandTag: "CAROLINA HERRERA",
      volume: "Eau de Parfum • 100ml",
      category: "perfumes",
      family: "oriental",
      intensity: "edp",
      occasion: "noite",
      sensation: "marcante",
      price: 484.90,
      oldPrice: 539.90,
      badge: "Edição Especial",
      image: "https://images.unsplash.com/photo-1523293182086-7651a899d37f?auto=format&fit=crop&w=900&q=85",
      notes: "Absinto, Anis Estrelado e Couro",
      similarIds: [15, 29, 22, 19]
    }),
    makeProduct({
      id: 26,
      title: "Giorgio Armani Acqua di Gio Absolu Masculino Eau de Parfum",
      brandTag: "GIORGIO ARMANI",
      volume: "Eau de Parfum • 75ml",
      category: "perfumes",
      family: "amadeirado",
      intensity: "edp",
      occasion: "noite",
      sensation: "marcante",
      price: 611.90,
      oldPrice: 679.90,
      badge: "",
      image: "https://images.unsplash.com/photo-1595425970377-c9703cf48b6d?auto=format&fit=crop&w=900&q=85",
      notes: "Toranja, Patchouli e Madeiras",
      similarIds: [18, 28, 19, 8]
    }),
    makeProduct({
      id: 27,
      title: "Animale Love Feminino Eau de Parfum",
      brandTag: "ANIMALE",
      volume: "Eau de Parfum • 100ml",
      category: "perfumes",
      family: "floral",
      intensity: "edp",
      occasion: "dia",
      sensation: "romantico",
      price: 310.90,
      oldPrice: 349.90,
      badge: "",
      image: "https://images.unsplash.com/photo-1590736969955-71cc94901144?auto=format&fit=crop&w=900&q=85",
      notes: "Frutas, Florais e Almíscar",
      similarIds: [16, 5, 6, 4]
    }),
    makeProduct({
      id: 28,
      title: "Giorgio Armani Acqua di Gio Masculino Eau de Toilette",
      brandTag: "GIORGIO ARMANI",
      volume: "Eau de Toilette • 200ml",
      category: "perfumes",
      family: "amadeirado",
      intensity: "edt",
      occasion: "dia",
      sensation: "marcante",
      price: 775.90,
      oldPrice: 849.90,
      badge: "Mais Vendido",
      image: "https://images.unsplash.com/photo-1615634260167-c8cdede054de?auto=format&fit=crop&w=900&q=85",
      notes: "Limão, Neroli e Cedro",
      similarIds: [18, 26, 19, 9]
    }),
    makeProduct({
      id: 29,
      title: "Carolina Herrera Bad Boy Cobalt Masculino Eau de Parfum",
      brandTag: "CAROLINA HERRERA",
      volume: "Eau de Parfum • 100ml",
      category: "perfumes",
      family: "amadeirado",
      intensity: "edp",
      occasion: "noite",
      sensation: "marcante",
      price: 529.90,
      oldPrice: 589.90,
      badge: "Lançamento",
      image: "https://images.unsplash.com/photo-1541643600914-78b084683601?auto=format&fit=crop&w=900&q=85",
      notes: "Gerânio, Sálvia e Couro",
      similarIds: [25, 22, 19, 8]
    })
  ],
  filters: {
    category: 'todos',
    maxPrice: PRICE_FILTER_MAX,
    badge: '',
    search: '',
    sortBy: 'populares',
    activeCategoryFilters: {}
  },
  cart: [],
  wishlist: [],
  shippingCost: 0,
  shippingOptionName: '',
  shippingInfo: null,
  couponCode: '',
  paymentMethod: 'pix'
};

const CATEGORY_FILTER_CONFIGS = {
  todos: {
    eyebrow: "Catálogo",
    title: "Todos os produtos",
    groups: [
      {
        id: "universos",
        name: "Categorias",
        type: "shortcuts",
        options: [
          { value: "perfumes", label: "Perfumes", icon: "fa-solid fa-wine-bottle" },
          { value: "kits", label: "Kits", icon: "fa-solid fa-gift" }
        ]
      },
      {
        id: "sensation",
        name: "Sensação",
        type: "checkbox",
        options: [
          { value: "romantico", label: "Romântico" },
          { value: "marcante", label: "Marcante" }
        ]
      },
      {
        id: "occasion",
        name: "Ocasião",
        type: "pills",
        options: [
          { value: "dia", label: "Dia a dia" },
          { value: "noite", label: "Noite" },
          { value: "festa", label: "Eventos" }
        ]
      }
    ]
  },
  perfumes: {
    eyebrow: "Perfumes",
    title: "Filtrar",
    groups: [
      {
        id: "family",
        name: "Família olfativa",
        type: "checkbox",
        options: [
          { value: "floral", label: "Floral" },
          { value: "amadeirado", label: "Amadeirado" },
          { value: "oriental", label: "Oriental" }
        ]
      },
      {
        id: "intensity",
        name: "Concentração",
        type: "checkbox",
        options: [
          { value: "edp", label: "Eau de Parfum" },
          { value: "edt", label: "Eau de Toilette" }
        ]
      },
      {
        id: "occasion",
        name: "Ocasião",
        type: "pills",
        options: [
          { value: "dia", label: "Dia a dia" },
          { value: "noite", label: "Noite" },
          { value: "festa", label: "Eventos" }
        ]
      }
    ]
  },
  kits: {
    eyebrow: "Kits",
    title: "Filtrar",
    groups: [
      {
        id: "giftPackaging",
        name: "Embalagem",
        type: "checkbox",
        options: [
          { value: "caixa-luxo", label: "Coffret / caixa" }
        ]
      },
      {
        id: "giftOccasion",
        name: "Ocasião",
        type: "pills",
        options: [
          { value: "amor", label: "Presente" }
        ]
      }
    ]
  },
  skincare: { eyebrow: "Skincare", title: "Filtrar", groups: [] },
  maquiagem: { eyebrow: "Maquiagem", title: "Filtrar", groups: [] },
  cabelos: { eyebrow: "Cabelos", title: "Filtrar", groups: [] },
  corpo: { eyebrow: "Corpo & Banho", title: "Filtrar", groups: [] }
};
